### ISSUE TITLE
Add ability to use query paramters

### ISSUE THREAD

**Issue by grydstedt** [otothea/yield-siftscience#1]
Thanks for the useful lib!

Siftscience allows for query params to get extra parameters on a response:

```
  var siftscience_event_request = function(_data, _callback) {
    var data = _.extend(_data, { '$api_key': _api_key });
    var opts = {
      method: 'POST',
      url: sift_url + "/events",
      body: JSON.stringify(data),
      json: true,
      qs: {
        return_action: true
      }
    };
    return siftscience_request(opts, _callback);
  };
```

Added:

```
      qs: {
        return_action: true
      }
```

Any way we can add an options object to pass in query params?

**Comment by otothea** [comment]
@grydstedt  Happy to implement. Would you mind linking me to the docs on this?

**Comment by grydstedt** [comment]
I think it's fairly undocumented unfortunately. the only option I know of is `return_action`.

**Comment by otothea** [comment]
@grydstedt I have implemented your request and then some. I have refactored the init to take 1 arg that is an object, instead of many args (it was starting to get pretty ugly). I have not updated the npm package. Can you use the latest git repo and make sure it is doing what you want now? Please refer to the latest README.md for updated usage and docs

**Comment by otothea** [comment]
I was able to find the limited documentation they do have: [return_action](https://siftscience.com/resources/tutorials/formulas#add-actions).

I have updated the package to 0.1.0 and this issue is resolved by requiring the package with the `return_action` set to true:

``` js
var siftscience = require('yield-siftscience')({
  api_key: 'YOUR_SIFT_SCIENCE_REST_API_KEY',
  return_action: true
});
```

Please check the change log at the bottom of the README for other added features.

**Comment by grydstedt** [comment]
Thank you! that works!
